package ipc

import (
	"bufio"
	"encoding/json"
	"log"
	"net"
	"os"
	"sync"
)

// Command represents a message sent from the host (Midipunk) to GUIPunk.
type Command struct {
	Action  string          `json:"action"`            // e.g., "LoadLayout", "UpdateComponent", "ShowKeyboard"
	Payload json.RawMessage `json:"payload,omitempty"` // Raw JSON of the command target
}

// Event represents a message generated by GUIPunk and sent to the host.
type Event struct {
	Type    string          `json:"type"`              // e.g., "ButtonPressed", "KeyboardInput", "TouchRelease"
	Payload json.RawMessage `json:"payload,omitempty"` // Raw JSON of the event data
}

// Server handles listening for UDS connections.
type Server struct {
	SocketPath string
	listener   net.Listener

	mu         sync.Mutex
	clientConn net.Conn

	Commands chan Command
	Events   chan Event
}

// NewServer creates a new IPC Server for GUIPunk.
func NewServer(socketPath string) *Server {
	return &Server{
		SocketPath: socketPath,
		Commands:   make(chan Command, 64),
		Events:     make(chan Event, 64),
	}
}

// Start begins listening on the Unix Domain Socket.
func (s *Server) Start() error {
	// Clean up any existing socket file
	if err := os.RemoveAll(s.SocketPath); err != nil {
		return err
	}

	ln, err := net.Listen("unix", s.SocketPath)
	if err != nil {
		return err
	}
	s.listener = ln
	log.Printf("IPC Server listening on %s\n", s.SocketPath)

	go s.acceptLoop()
	go s.sendLoop()

	return nil
}

// Stop closes the Unix Domain Socket listener and active connection.
func (s *Server) Stop() {
	s.mu.Lock()
	if s.clientConn != nil {
		s.clientConn.Close()
	}
	s.mu.Unlock()

	if s.listener != nil {
		s.listener.Close()
	}
}

// acceptLoop handles accepting new incoming connections.
func (s *Server) acceptLoop() {
	for {
		conn, err := s.listener.Accept()
		if err != nil {
			log.Println("UDS accept error:", err)
			return
		}

		log.Println("Host connected to IPC UDS")

		s.mu.Lock()
		// If an old connection exists, close it (only allow 1 host connecting at a time)
		if s.clientConn != nil {
			s.clientConn.Close()
		}

		s.clientConn = conn
		s.mu.Unlock()

		go s.handleConnection(conn)
	}
}

// handleConnection reads line-delimited JSON commands from the connection.
func (s *Server) handleConnection(conn net.Conn) {
	scanner := bufio.NewScanner(conn)
	for scanner.Scan() {
		line := scanner.Bytes()
		var cmd Command
		if err := json.Unmarshal(line, &cmd); err != nil {
			log.Printf("Failed to unmarshal command: %v (raw: %s)\n", err, string(line))
			continue
		}
		s.Commands <- cmd
	}

	if err := scanner.Err(); err != nil {
		log.Printf("UDS Scanner error: %v\n", err)
	}

	log.Println("Host disconnected from IPC UDS")

	s.mu.Lock()
	// Only nil out the clientConn if it hasn't been replaced by a new connection
	if s.clientConn == conn {
		s.clientConn = nil
	}
	s.mu.Unlock()
}

// sendLoop reads events from the channel and broadcasts them down the UDS to the host.
func (s *Server) sendLoop() {
	for event := range s.Events {
		s.mu.Lock()
		conn := s.clientConn
		s.mu.Unlock()

		if conn == nil {
			continue // No active client connected, drop an event rather than panic
		}

		b, err := json.Marshal(event)
		if err != nil {
			log.Printf("Failed to marshal event: %v\n", err)
			continue
		}
		b = append(b, '\n') // Newline separator for JSON protocol

		if _, err := conn.Write(b); err != nil {
			log.Printf("Failed to write event to host: %v\n", err)
			s.mu.Lock()
			// Ensure we are closing and clearing the connection that just failed
			if s.clientConn == conn {
				s.clientConn.Close()
				s.clientConn = nil
			}
			s.mu.Unlock()
		}
	}
}
